name: vaccine_effectiveness
channels:
  - conda-forge
dependencies:
 - quarto=1.3.450
 - r-base=4.2
#  - r-grDevices
#  - r-consort
#  - r-parallel
 - r-devtools=2.4
 - r-quarto=1.2
 - r-arrow=10.0.1
 - r-dplyr=1.1.2
 - r-validate=1.1.3
 - r-dataexplorer=0.8.2
 - r-dt=0.27
 - r-purrr=1.0.1
 - r-dlookr=0.6.1
 - r-ggpubr=0.5.0
 - r-survminer=0.4.9
 - r-ggplot2=3.4.0
 - r-plotly=4.10.2
 - r-scales=1.2.1
 - r-formattable=0.2.1
 - r-naniar=0.6.1
 - r-duckdb=0.6.2
 - r-dbi=1.1.3
 - r-here=1.0.1
 - r-renv=0.17.3 
 - r-visdat=0.6.0
 - r-mice=3.15.0
 - r-tidyr=1.3.0
 - r-shiny=1.7.4
 - r-shinydashboard=0.7.2
 - r-shinyjs=2.1.0
 - r-matchit=4.5.0
 - r-survival=3.5
 - r-table1=1.4.3
 - r-knitr=1.41
 # - r-tab=5.1
 - r-forestmodel=0.6.2
 - r-gtsummary=1.7.2
 # - r-survrm2=1.0.4
 - r-log4R=0.4.3
 - r-xlsx=0.6.5
 - r-finalfit=1.0.6
 - r-dbplyr=2.3
 - r-htmlwidgets=1.6.2