name: vaccine_effectiveness
channels:
  - conda-forge
dependencies:
  - r-base=4.2
  - r-devtools=2.4
  - quarto=1.1.145
  - r-quarto=1.2
  - r-arrow=10.0.1
  - r-dplyr=1.1
  - r-validate=1.1
  - r-dataexplorer=0.8.2
  - r-dt=0.27
  - r-purrr=1.0
  - r-dlookr=0.6.1
  - r-survminer=0.4.9
  - r-ggplot2=3.4
  - r-plotly=4.10
  - r-scales=1.2
  - r-formattable=0.2.1
  - r-naniar=1.0
  - r-duckdb=0.6.2
  - r-dbi=1.1
  - r-here=1.0
    #  - r-grDevices
  - r-visdat=0.6.0
  - r-mice=3.15
  - r-tidyr=1.3
  - r-shiny=1.7
    #  - r-consort
    #  - r-parallel
  - r-matchit=4.5
  - r-survival=3.5
  - r-table1=1.4
    #  - r-tab
  - r-forestmodel=0.6.2
  - r-gtsummary=1.7
    #  - r-survrm2


